# This viminfo file was generated by Vim 7.3.
# You may edit it if you're careful!

# Value of 'encoding' when this file was written
*encoding=utf-8


# hlsearch on (H) or off (h):
~h
# Last Search Pattern:
~MSle0~/gedit

# Last Substitute String:
$

# Command Line History (newest to oldest):
:wviminfo /home/svli/spec/codebreakder/viminfo.vim
:pwd
:wviminfo .
:wviminfo 
:colorscheme railscasts@7li
:wq
:q

# Search String History (newest to oldest):
? \Vsc\%#
?/mouse

# Expression History (newest to oldest):

# Input Line History (newest to oldest):

# Input Line History (newest to oldest):

# Registers:
""0	CHAR	0
	end
"1	LINE	0
	
"2	LINE	0
	  pending # express the regexp above with the code you wish you had
"3	LINE	0
	
"4	LINE	0
	
"5	LINE	0
	
"6	CHAR	0
	Given /^the secret code is "(.*?)"$/ do |arg1|
	  pending # express the regexp above with the code you wish you had
	end
"7	CHAR	0
	Given /^the secret code is "(.*?)"$/ do |arg1|
	  pending # express the regexp above with the code you wish you had
	end
	
"-	CHAR	0
	end

# File marks:
'0  32  0  ~/spec/codebreakder/features/step_definitions/codebreaker_steps.rb
'1  17  22  ~/spec/codebreakder/features/step_definitions/codebreaker_steps.rb
'2  41  2  ~/spec/codebreakder/features/step_definitions/codebreaker_steps.rb
'3  45  2  ~/spec/codebreakder/features/step_definitions/codebreaker_steps.rb
'4  33  23  ~/spec/codebreakder/features/step_definitions/codebreaker_steps.rb
'5  16  24  ~/rails/myapp/spec/codebreaker/features/codebreaker_submits_game.feature
'6  41  15  ~/rails/myapp/config/database.yml
'7  6  24  ~/rails/myapp/app/views/layouts/application.html.erb
'8  1  0  ~/rails/myapp/config/environment.rb
'9  32  0  ~/.vimrc.after

# Jumplist (newest first):
-'  32  0  ~/spec/codebreakder/features/step_definitions/codebreaker_steps.rb
-'  17  22  ~/spec/codebreakder/features/step_definitions/codebreaker_steps.rb
-'  8  0  ~/spec/codebreakder
-'  41  2  ~/spec/codebreakder/features/step_definitions/codebreaker_steps.rb
-'  22  0  ~/spec/codebreakder/features/step_definitions/codebreaker_steps.rb
-'  2  3  ~/spec/codebreakder/features/step_definitions/codebreaker_steps.rb
-'  31  36  ~/spec/codebreakder/features/step_definitions/codebreaker_steps.rb
-'  7  26  ~/spec/codebreakder/lib/codebreaker/game.rb
-'  1  0  ~/spec/codebreakder/lib/codebreaker/game.rb
-'  21  0  ~/spec/codebreakder
-'  45  2  ~/spec/codebreakder/features/step_definitions/codebreaker_steps.rb
-'  33  0  ~/spec/codebreakder
-'  45  0  ~/spec/codebreakder
-'  33  23  ~/spec/codebreakder/features/step_definitions/codebreaker_steps.rb
-'  57  0  ~/spec/codebreakder
-'  69  0  ~/spec/codebreakder
-'  16  24  ~/rails/myapp/spec/codebreaker/features/codebreaker_submits_game.feature
-'  7  15  ~/rails/myapp/spec/codebreaker/NERD_tree_1
-'  11  4  ~/rails/myapp/spec/codebreaker/NERD_tree_1
-'  1  2  ~/rails/myapp/spec/codebreaker/NERD_tree_1
-'  8  0  ~/rails/myapp/spec/codebreaker
-'  41  15  ~/rails/myapp/config/database.yml
-'  31  21  ~/rails/myapp/config/database.yml
-'  13  35  ~/rails/myapp/config/application.rb
-'  1  0  ~/rails/myapp/Gemfile.lock
-'  8  0  ~/rails/myapp
-'  6  24  ~/rails/myapp/app/views/layouts/application.html.erb
-'  1  0  ~/rails/myapp/app/views/layouts/application.html.erb
-'  33  0  ~/rails/myapp
-'  1  0  ~/rails/myapp/config/environment.rb
-'  1  0  ~/rails/myapp/config/routes.rb
-'  1  0  ~/rails/myapp/public/422.html
-'  1  0  ~/rails/myapp/public/500.html
-'  1  0  ~/rails/myapp/config/database.yml
-'  1  0  ~/rails/myapp/config/boot.rb
-'  1  0  ~/rails/myapp/config/application.rb
-'  57  0  ~/rails/myapp
-'  32  0  ~/.vimrc.after
-'  16  24  ~/rails/myapp/spec/codebreaker/features/codebreaker_submits_game.feature
-'  7  15  ~/rails/myapp/spec/codebreaker/NERD_tree_1
-'  11  4  ~/rails/myapp/spec/codebreaker/NERD_tree_1
-'  1  2  ~/rails/myapp/spec/codebreaker/NERD_tree_1
-'  8  0  ~/rails/myapp/spec/codebreaker
-'  41  15  ~/rails/myapp/config/database.yml
-'  31  21  ~/rails/myapp/config/database.yml
-'  13  35  ~/rails/myapp/config/application.rb
-'  1  0  ~/rails/myapp/Gemfile.lock
-'  8  0  ~/rails/myapp
-'  6  24  ~/rails/myapp/app/views/layouts/application.html.erb
-'  1  0  ~/rails/myapp/app/views/layouts/application.html.erb
-'  33  0  ~/rails/myapp
-'  1  0  ~/rails/myapp/config/environment.rb
-'  1  0  ~/rails/myapp/config/routes.rb
-'  1  0  ~/rails/myapp/public/422.html
-'  1  0  ~/rails/myapp/public/500.html
-'  1  0  ~/rails/myapp/config/database.yml
-'  1  0  ~/rails/myapp/config/boot.rb
-'  1  0  ~/rails/myapp/config/application.rb
-'  57  0  ~/rails/myapp
-'  32  0  ~/.vimrc.after
-'  16  24  ~/rails/myapp/spec/codebreaker/features/codebreaker_submits_game.feature
-'  7  15  ~/rails/myapp/spec/codebreaker/NERD_tree_1
-'  11  4  ~/rails/myapp/spec/codebreaker/NERD_tree_1
-'  1  2  ~/rails/myapp/spec/codebreaker/NERD_tree_1
-'  8  0  ~/rails/myapp/spec/codebreaker
-'  41  15  ~/rails/myapp/config/database.yml
-'  31  21  ~/rails/myapp/config/database.yml
-'  13  35  ~/rails/myapp/config/application.rb
-'  1  0  ~/rails/myapp/Gemfile.lock
-'  8  0  ~/rails/myapp
-'  6  24  ~/rails/myapp/app/views/layouts/application.html.erb
-'  1  0  ~/rails/myapp/app/views/layouts/application.html.erb
-'  33  0  ~/rails/myapp
-'  1  0  ~/rails/myapp/config/environment.rb
-'  1  0  ~/rails/myapp/config/routes.rb
-'  1  0  ~/rails/myapp/public/422.html
-'  1  0  ~/rails/myapp/public/500.html
-'  1  0  ~/rails/myapp/config/database.yml
-'  1  0  ~/rails/myapp/config/boot.rb
-'  1  0  ~/rails/myapp/config/application.rb
-'  57  0  ~/rails/myapp
-'  32  0  ~/.vimrc.after
-'  16  24  ~/rails/myapp/spec/codebreaker/features/codebreaker_submits_game.feature
-'  7  15  ~/rails/myapp/spec/codebreaker/NERD_tree_1
-'  11  4  ~/rails/myapp/spec/codebreaker/NERD_tree_1
-'  1  2  ~/rails/myapp/spec/codebreaker/NERD_tree_1
-'  8  0  ~/rails/myapp/spec/codebreaker
-'  41  15  ~/rails/myapp/config/database.yml
-'  31  21  ~/rails/myapp/config/database.yml
-'  13  35  ~/rails/myapp/config/application.rb
-'  1  0  ~/rails/myapp/Gemfile.lock
-'  8  0  ~/rails/myapp
-'  6  24  ~/rails/myapp/app/views/layouts/application.html.erb
-'  1  0  ~/rails/myapp/app/views/layouts/application.html.erb
-'  33  0  ~/rails/myapp
-'  32  0  ~/spec/codebreakder/features/step_definitions/codebreaker_steps.rb
-'  17  22  ~/spec/codebreakder/features/step_definitions/codebreaker_steps.rb

# History of marks within files (newest to oldest):

> ~/spec/codebreakder/features/step_definitions/codebreaker_steps.rb
	"	32	0
	^	1	6
	.	1	5
	+	34	0
	+	33	0
	+	34	46
	+	37	0
	+	35	38
	+	36	19
	+	33	0
	+	31	0
	+	32	0
	+	31	0
	+	2	0
	+	1	0
	+	1	5
